apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: whatsapp
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/biswajit134/whatsapp-devops/backend:latest
          ports:
            - containerPort: 9000
          env:
            - name: PORT
              value: "9000"
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              value: mongodb://mongo:27017/whatsappdb
            - name: FRONTEND_URL
              value: http://localhost
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: whatsapp
  labels:
    app: backend
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: backend
