{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reels.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reels.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  MONGO_URI: {{ .Values.config.mongoUri | quote }}
{{- end }}
